data_source: examples/mortgage/data/loans.csv
format: csv
ontology: examples/mortgage/ontology/mortgage.ttl
target_class: http://example.com/MyClass
iri_template: http://example.com/MyClass/{id}
priority: balanced
use_semantic: true
streaming: false
output_format: turtle
output: output.turtle
validate: true
shapes: examples/mortgage/shapes/mortgage_shapes.ttl
use_graph_reasoning: true
use_history: true
enable_logging: true
log_file: rdfmap.log
